Updated DEB installer configurations  Added local HTTPS check before ending installation with timeout of 90 seconds  Checked and set required dependencies and put most others under recommends  Added Program Access message /w IP after install (Only shows if installed with CLI or looking in Logs) Removed IP message for upgrade scripts (show when they install Debian package anyway) Added timeout to edit configurations script when checking if HTTPS is responding Misc refactoring shell script files

diff --git a/extras/deb_package_files/DEBIAN/postinst b/extras/deb_package_files/DEBIAN/postinst
--- a/extras/deb_package_files/DEBIAN/postinst
+++ b/extras/deb_package_files/DEBIAN/postinst
@@ -2,28 +2,38 @@
 PYTHON_VENV_DIR="/home/kootnet_data/env"
 INSTALL_DIR="/opt/kootnet-sensors"
 CONFIG_DIR="/etc/kootnet"
-if [[ ! -f ${PYTHON_VENV_DIR}/bin/python ]]
-then
- python3 -m venv --system-site-packages ${PYTHON_VENV_DIR}
- ${PYTHON_VENV_DIR}/bin/python3 -m pip install -U pip
- date > ${CONFIG_DIR}/installed_datetime.txt
+if [[ ! -f ${PYTHON_VENV_DIR}/bin/python ]]; then
+  python3 -m venv --system-site-packages ${PYTHON_VENV_DIR}
+  ${PYTHON_VENV_DIR}/bin/python3 -m pip install -U pip
+  date >${CONFIG_DIR}/installed_datetime.txt
 fi
 ${PYTHON_VENV_DIR}/bin/pip3 install -r ${INSTALL_DIR}/requirements.txt
-if [[ ! -f ${CONFIG_DIR}/installed_datetime.txt ]]
-then
- date > ${CONFIG_DIR}/installed_datetime.txt
+if [[ ! -f ${CONFIG_DIR}/installed_datetime.txt ]]; then
+  date >${CONFIG_DIR}/installed_datetime.txt
 fi
-echo '*/1 * * * * fake-hwclock' >> /tmp/tmp34441.txt
+echo '*/1 * * * * fake-hwclock' >>/tmp/tmp34441.txt
 crontab -u root /tmp/tmp34441.txt
 rm /tmp/tmp34441.txt
-date > ${CONFIG_DIR}/last_updated.txt
-echo ' - DEB' >> ${CONFIG_DIR}/last_updated.txt
+date >${CONFIG_DIR}/last_updated.txt
+echo ' - DEB' >>${CONFIG_DIR}/last_updated.txt
 systemctl daemon-reload
 systemctl enable KootnetSensors
 systemctl start KootnetSensors
 printf "\n\nWaiting for program initalization to finish...\n\n"
-while [ "$(wget --no-check-certificate -q -O - "https://localhost:10065/CheckOnlineStatus")" != "OK" ]
-do
+counter=0
+while true; do
+  if [[ "$(wget --no-check-certificate -q -O - "https://localhost:10065/CheckOnlineStatus")" == "OK" ]]; then
+    printf "Initalization Complete\n\n"
+    printf 'Open https://localhost:10065 on the local sensor to configure\n\n'
+    printf 'To access the sensor from another device, replace "localhost" with an IP\n'
+    printf 'IP addresses show below  ** Note: 127.0.0.1 is the same as localhost **\n\n'
+    ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
+    printf '\n'
+    exit 0
+  elif [ "$counter" -gt 45 ]; then
+    printf "Timeout: Problem Initalizing Application, missing requirements?\n\n"
+    exit 1
+  fi
   sleep 2
+  counter=$((counter + 1))
 done
-printf "Initalization Complete\n\n"
